/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import static interfaces.Interfaz.cardLayout;
import static interfaces.Interfaz.nombreUsuario;
import static interfaces.Interfaz.panelPadreLayout;
import java.awt.Color;

/**
 *
 * @@Galvys Rodriguez
 */
public class DialogPeticionNombre extends javax.swing.JDialog {
    
    
    
    /**
     * Creates new form DialogPeticionNombre
     * @param parent
     * @param modal
     */
    public DialogPeticionNombre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public boolean validarNombre() {
        int cantidad = campoNombre.getText().trim().length();
        if (cantidad > 2 && cantidad < 20) {
            return true;
        }else{
            mensajesError.setText("Debe ingresar un nombre entre 3 y 19 carácteres");
            return false;  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDialog = new javax.swing.JPanel();
        campoNombre = new javax.swing.JTextField();
        mensajesError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDialog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNombre.setFont(new java.awt.Font("Montserrat", 0, 36)); // NOI18N
        campoNombre.setForeground(new java.awt.Color(102, 102, 102));
        campoNombre.setText("Nombre De Usuario");
        campoNombre.setBorder(null);
        campoNombre.setOpaque(false);
        campoNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNombreFocusLost(evt);
            }
        });
        panelDialog.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 155, 620, 40));

        mensajesError.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        mensajesError.setForeground(new java.awt.Color(204, 0, 0));
        panelDialog.add(mensajesError, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        panelDialog.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 600, -1));

        botAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botAceptar.png"))); // NOI18N
        botAceptar.setBorder(null);
        botAceptar.setBorderPainted(false);
        botAceptar.setContentAreaFilled(false);
        botAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAceptarActionPerformed(evt);
            }
        });
        panelDialog.add(botAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoDialog.png"))); // NOI18N
        panelDialog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panelDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAceptarActionPerformed
        if (validarNombre()) {
            setVisible(false);
            nombreUsuario = campoNombre.getText();
            cardLayout.show(panelPadreLayout, "cardPrincipal");
        }
    }//GEN-LAST:event_botAceptarActionPerformed

    private void campoNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusGained
        if(campoNombre.getText().matches("Nombre De Usuario")){
            campoNombre.setText("");
            campoNombre.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoNombreFocusGained

    private void campoNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNombreFocusLost
        if(campoNombre.getText().trim().isEmpty()){
            campoNombre.setText("Nombre De Usuario");
            campoNombre.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_campoNombreFocusLost

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAceptar;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mensajesError;
    private javax.swing.JPanel panelDialog;
    // End of variables declaration//GEN-END:variables
}
